version: '3'
services:
  app:
    environment:
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=Winner2001.
      - MYSQL_DATABASE=aidateml
      - DB_HOST=aidateml.ccdlv7vo5t4q.us-east-1.rds.amazonaws.com
      - ALLOWED_HOSTS=*
  nginx:
    environment:
      - AIDATEML_APP_PORT=9000
    ports:
    - "9000:80"
