version: '3'
services:
  postgres:
    container_name: ntsprint-aidateai-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: aidate
      POSTGRES_PASSWORD: aidate
      POSTGRES_DB: assitantdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: ntsprint-aidateai-rabbitmq
    image: "rabbitmq:3.8-management"
    ports:
      - "15672:15672"
      - "5672:5672"

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./assistant_enterview:/app
    depends_on:
      - postgres
      - rabbitmq
    command: ["python", "api.py"] # Puedes cambiar "api.py" por el archivo que quieras ejecutar
volumes:
  postgres_data: