version: "3"

volumes:
  db_data: {}
  audio_data: {}

services:
  app:
    container_name: aidateai_prod_app
    build:
      context: .
      dockerfile: docker/production/app/Dockerfile
    volumes:
      - ./fastapi_enterview:/app
      - audio_data:/app/audios
    command: /start

  nginx:
    container_name: aidateai_prod_nginx
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    depends_on:
      - app
    volumes:
      - audio_data:/usr/share/nginx/audios
