/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demoassistantinterface;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import python.RunScriptPython;

/**
 *
 * @author ADRIEL WORKS
 */
public class AsistenteVirtualGUI extends javax.swing.JFrame {

    /**
     * Creates new form AsistenteVirtualGUI
     */
    private ImageIcon imagenGifMicro;
    private ImageIcon imagenJpgMicro;
    private boolean gifMostrado = false;
    private RunScriptPython runScriptPython;
    private String pathScriptApi = "F:\\NTSprint\\work\\AIDateAI\\AIDateAI\\projects\\assistant_enterview\\api.py";
    private String pathPython = "F:\\NTSprint\\work\\envai\\Scripts\\python.exe";
    
    public AsistenteVirtualGUI() {
        initComponents();
        // Centra la ventana en la pantalla
        this.setLocationRelativeTo(null);

        // Desactiva la maximización
        this.setResizable(false);
        
        imagenGifMicro = new ImageIcon(getClass().getResource("/demoassistantinterface/img/micro.gif")); // Asegúrate de que la imagen GIF esté en el paquete 'img'
        imagenJpgMicro = new ImageIcon(getClass().getResource("/demoassistantinterface/img/micro_static.jpg")); // Asegúrate de que la imagen JPG esté en el paquete 'img'
        
    }
    
    private void cambiarImagen() {
        if (gifMostrado) {
            labelMicrophone.setIcon(imagenJpgMicro);
        } else {
            labelMicrophone.setIcon(imagenGifMicro);
        }
        gifMostrado = !gifMostrado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMicrophone = new javax.swing.JLabel();
        buttonNextQuestion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelAssistant = new javax.swing.JPanel();
        labelAssitant = new javax.swing.JLabel();
        buttonStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DEMO ASSISTANT INTERVIEWS");

        labelMicrophone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoassistantinterface/img/micro_static.jpg"))); // NOI18N
        labelMicrophone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMicrophoneMouseClicked(evt);
            }
        });

        buttonNextQuestion.setText(">>Next Question");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        labelAssitant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demoassistantinterface/img/assistant.png"))); // NOI18N

        javax.swing.GroupLayout panelAssistantLayout = new javax.swing.GroupLayout(panelAssistant);
        panelAssistant.setLayout(panelAssistantLayout);
        panelAssistantLayout.setHorizontalGroup(
            panelAssistantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAssistantLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(labelAssitant)
                .addGap(14, 14, 14))
        );
        panelAssistantLayout.setVerticalGroup(
            panelAssistantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAssistantLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelAssitant)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        buttonStart.setText("Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(panelAssistant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMicrophone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNextQuestion))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAssistant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonNextQuestion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonStart)
                            .addComponent(labelMicrophone))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelMicrophoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMicrophoneMouseClicked
        // TODO add your handling code here:
        cambiarImagen();
    }//GEN-LAST:event_labelMicrophoneMouseClicked

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        // TODO add your handling code here:
        runScriptPython = new RunScriptPython(pathScriptApi,pathPython);
        String path = "F:\\NTSprint\\work\\AIDateAI\\AIDateAI\\projects\\assistant_enterview\\presentation.txt";
        runScriptPython.createPathRoot("F:\\NTSprint\\work\\AIDateAI\\AIDateAI\\projects\\assistant_enterview");
        //runScriptPython.createPathPresentation(path);
        runScriptPython.createNewPresentation("\"'Everyone's journey is unique, and I'd love to hear about yours."
                + " Feel free to share as much as you're comfortable with in this safe, private space. Ready?\"'");
        runScriptPython.speakPresentation();
        
//        File archivo = new File(pathScriptApi);
//
//        if (archivo.exists()) {
//            System.out.println("El archivo existe en la ruta especificada.");
//        } else {
//            System.out.println("El archivo no existe en la ruta especificada.");
//        }
    }//GEN-LAST:event_buttonStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsistenteVirtualGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsistenteVirtualGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsistenteVirtualGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsistenteVirtualGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
        } catch (Exception e) {
            //
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsistenteVirtualGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNextQuestion;
    private javax.swing.JButton buttonStart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAssitant;
    private javax.swing.JLabel labelMicrophone;
    private javax.swing.JPanel panelAssistant;
    // End of variables declaration//GEN-END:variables
}
